name: Publish Dry Run

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-dry-run:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Release dry run
        run: bun run release:dry
